import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { DM_Sans } from "next/font/google";
import "./globals.css";
// import db from "@/lib/supabase/db";
// import { log } from "console";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/lib/providers/next-theme-providers";

const dm_sans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Notion clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(db);
  return (
    <html
      lang="en"
      className={cn("bg-background", "h-full", "antialiased",
        dm_sans, "font-sans", inter.className)}
      suppressHydrationWarning
    >
      <body className=
        "min-h-full flex flex-col"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
